_target_: rul_datasets.RulDataModule
reader:
  _target_: rul_datasets.XjtuSyReader
  fd: ???
  norm_rul: True
  truncate_degraded_only: True
batch_size: 64
feature_extractor:
  _target_: crule.run.utils.XjtuSyWindowExtractor
  upper_window: 20
  lower_window: 2560
