# @package _global_

defaults:
  - approach_base

runner: crule.run.mmd

dm:
  _target_: rul_datasets.DomainAdaptionDataModule

training:
  approach:
      _target_: rul_adapt.approach.MmdApproach
      lr: ???
      mmd_factor: ???
      num_mmd_kernels: ???
      loss_type: rmse
